### ISSUE TITLE
Save to correct Unix path

### ISSUE THREAD

**Issue by tmichels** [alexspurven/ttbin2tcx#1]
Hi Alex, congrats on the application, it looks really neat, nice coding! But when I try to run this on my Ubuntu, TCX is saved to a path like this (note last backslash instead of forward): `../TomTomWatch/working/ttbin\running-20230925214311.tcx` 

I created a fix that should work on Linux, MacOS and Windows, but I cannot push to a new branch. But if you want to you can replace 3 lines of code from line 42 of main.py with this:

```
    fileNameTcx = "%s-%s.tcx" % (activity.activityType.name.lower(), dt.strftime("%Y%m%d%H%M%S"))
    pathTcx = os.path.join(dir, fileNameTcx)
    writer = TcxFileWriter()
    writer.SaveActivity(pathTcx, activity)
```

**Comment by alexspurven** [comment]
Hi
Yes, thanks, I will test and apply.
Best regards

fre. 29. sep. 2023 kl. 22:36 skrev tmichels ***@***.***>:
