### ISSUE TITLE
Tag: 0x2d Pos: 0xf7 is not implemented. Exiting

### ISSUE THREAD

**Issue by tmichels** [alexspurven/ttbin2tcx#2]
When attempting to convert the attached ttbin, I end up with an empty tcx and below error:
"Tag: 0x2d Pos: 0xf7 is not implemented. Exiting". 
![afbeelding](https://github.com/alexspurven/ttbin2tcx/assets/47347917/79b05276-5b66-4b66-89f8-d20507f44f04)

TTBIN file: 
[7okt.ttbin.gz](https://github.com/alexspurven/ttbin2tcx/files/12850480/7okt.ttbin.gz) 
Resulting TCX file: 
[running-20231007102618.tcx.gz](https://github.com/alexspurven/ttbin2tcx/files/12850499/running-20231007102618.tcx.gz)

(both files packaged in order to being able to upload it to github)

I debugged and tried to add an implementation to ttbinreader.py, but to be honest I have no clue what I was doing and it didn't work out... Would you maybe provide any guidance so that I can help you implement this?

**Comment by alexspurven** [comment]
Was it a swimming?

**Comment by tmichels** [comment]
Oh you are a hero! It works now and as you must be well aware now, this was not a swimming, but a running activity with manual lap separations! Thanks a lot, so happy I can still use my TomTom watch! Now let's hope the watch will keep connecting to the satellites, but this is great work! Thanks again and let me know if there is anything I can help you with.

**Comment by alexspurven** [comment]
Guick gps update is still working, hope they are used it not only for watches.

> As QuickGPS data will no longer be available it might take longer for your watch to obtain a GPS fix

As I understand this means that they should work anyway

> happy I can still use my TomTom watch

Happy too. There are no such good watches in the market now
